### ISSUE TITLE
Suggestion: AllArgsConstructor, RequiredArgsConstructor and NoArgsConstructor?

### ISSUE THREAD

**Issue by natureventyrnu** [chaowlert/PrimaryConstructor#2]
Hi
Thank you for this plugin. Project lombok (for java) has:
- AllArgsConstructor : Generates a constructor with all members
- RequiredArgsConstructor: Generates a constructor for all final/readonly members
- NoArgsConstructor: Generates empty constructor

Any plans for implementing something like this? Currently I'm having some classes, that just needs a constructor that takes all arguments, but I cannot make them readonly as they need to be updated through their properties

**Comment by fabionaspolini** [comment]
I implemented the IgnorePrimaryConstructor attribute and adding support to read-only properties at the pull request https://github.com/chaowlert/PrimaryConstructor/pull/4.

**Comment by fabionaspolini** [comment]
@chaowlert, can you publish a new version on NuGet?

**Comment by chaowlert** [comment]
@fabionaspolini thx u for PR, I also add `[IncludePrimaryConstructor]` for including fields not annotated with readonly.
