### ISSUE TITLE
Property or indexer cannot be assigned to - it is read only

### ISSUE THREAD

**Issue by vladk** [chaowlert/PrimaryConstructor#5]
`I'm` getting compile error "Property or indexer 'MyDependency.name' cannot be assigned to -- it is read only" when there is read-only property with expression body.

Code to reproduce the bug:

```csharp
    [PrimaryConstructor]
    public partial class MyDependency
    {
        public string GetName()
        {
            return "Hello";
        }
        private string name => GetName();
    }
```

**Comment by chaowlert** [comment]
Sorry, I just add readonly property support, but missed the method body case. Just release 1.3.1, pls test.

**Comment by vladk** [comment]
thanks, issue is resolved in latest version
