### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by shadeglare** [chaowlert/PrimaryConstructor#7]
There can be namespace collisions when a namespace has a subspace and this subspace name is used as the root namespace in another project.
To resolve the problem the generated constructor should generate parameters with the `global` keyword:
```cs
global::Name.Space.TypeName x
```

**Comment by alexandersorokin** [comment]
In case this repo is dead, I have fixed it here: https://github.com/skbkontur/PrimaryConstructor/commit/064c1bbe23bbc017ee77a7711f0ddb1768f64702
